apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dopplersecret-other-to-self
  namespace: default
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: default
  managedSecret:
    name: dopplersecret-other-to-self
    namespace: default
    type: Opaque
  project: k8s-demo
  config: dev