apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dopplersecret-tls
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  managedSecret:
    name: dopplersecret-tls
    namespace: default
    type: kubernetes.io/tls
  project: k8s-demo
  config: dev
  secrets:
    - TLS_CRT
    - TLS_KEY
  processors:
    TLS_CRT:
      type: base64
      asName: tls.crt
    TLS_KEY:
      type: base64
      asName: tls.key