# THIS WILL FAIL!! You aren't allowed to reference or create secrets in
# namespaces outside of where the CRD is created unless it exists in the
# operator namespace.
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dopplersecret-other-to-operator
  namespace: default
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: default
  managedSecret:
    name: dopplersecret-other-to-operator
    namespace: doppler-operator-system
    type: Opaque
  project: k8s-demo
  config: dev