apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dopplersecret-subsecrets
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  managedSecret:
    name: dopplersecret-subsecrets
    namespace: default
    type: Opaque
  project: k8s-demo
  config: dev
  secrets:
    - FOO
    - BAR
  processors:
    FOO:
      type: plain
      asName: foo