apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dopplersecret-dockerconfigjson
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  managedSecret:
    name: doppler-dockerconfigjson
    namespace: default
    type: kubernetes.io/dockerconfigjson
  project: k8s-demo
  config: dev
  processors:
    DOCKER_CONFIG_JSON:
      type: plain
      asName: ".dockerconfigjson"