apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-api-pkcs12
  namespace: external-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-auth-api

  target:
    name: auth-api-pkcs12
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .cert | pkcs12certPass .pass }}"
        tls.key: "{{ .cert | pkcs12keyPass .pass }}"

  data:
  # this is a pkcs12 archive that contains a cert and a private key
  - secretKey: cert
    remoteRef:
      key: PKCS12_CRT
      decodingStrategy: Base64
  - secretKey: pass
    remoteRef:
      key: PKCS12_PASS