apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-api-single
  namespace: external-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-auth-api

  target:
    name: auth-api-single

  data:
      # sync just the "MONGO_URL" secret and use the key "mongo-url" in k8s
    - secretKey: mongo-url
      remoteRef:
        key: MONGO_URL