apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-api-path
  namespace: external-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-auth-api

  target:
    name: auth-api-path

  dataFrom:
      # only sync the secrets with the "MONGO_" prefix
    - find:
        path: MONGO_