apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-api-rewrite
  namespace: external-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-auth-api

  target:
    name: auth-api-rewrite

  dataFrom:
      # limit to just secrets starting with "DEVOPS_"
    - find:
        path: DEVOPS_
      # rewrite the secret, removing the "DEVOPS_" prefix
      rewrite:
      - regexp:
          source: "DEVOPS_(.*)"
          target: "$1"