apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-api-tls
  namespace: external-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-auth-api

  target:
    name: auth-api-tls
    template:
      type: kubernetes.io/tls

  data:
      # sync the "TLS_CRT" and "TLS_KEY" secrets, base64 decode them, and set
      # them to the "tls.crt" and "tls.key" keys
    - secretKey: tls.crt
      remoteRef:
        key: TLS_CRT
        decodingStrategy: Base64
    - secretKey: tls.key
      remoteRef:
        key: TLS_KEY
        decodingStrategy: Base64